sleep to avoid race condition when encrypting key
we tee the random key data into two simultaneous processes to avoid
landing the unencrypted key to the filesystem. This caused a
race condition as the key encryption was not gauranteed to finish prior
to trying to combine the encrypted data into the final output.

touching a file when done, and checking for the existence of that file,
should close the race. This is a quick&dirty fix, but if you weren't
okay with quick&dirty, you wouldn't be wrapping openssl commands in a
bash script anyway.

diff --git a/locker b/locker
--- a/locker
+++ b/locker
@@ -72,8 +72,13 @@ else
 
 	openssl rand -base64 128 |
 	tee \
-		>( openssl rsautl -encrypt -inkey "$pubkey" -pubin -in /dev/stdin -out "$TEMP/key.bin.enc" ) \
+		>( openssl rsautl -encrypt -inkey "$pubkey" -pubin -in /dev/stdin -out "$TEMP/key.bin.enc" && touch "$TEMP/key.bin.ok" || touch "$TEMP/key.bin.fail" ) \
 		| openssl enc -aes-256-cbc -salt -in "$input" -out "$TEMP/payload.bin.enc" -pass fd:0
 
+	while [[ ! -e "$TEMP/key.bin.ok" ]] && [[ ! -e "$TEMP/key.bin.fail" ]]; do sleep 0.001; done
+	if [[ -e "$TEMP/key.bin.fail" ]]; then
+		printf 'Failed to encrypt random key\n' >&2
+		exit 1
+	fi
 	tar --transform='s#.*/##' -zcf "$output" "$TEMP/payload.bin.enc" "$TEMP/key.bin.enc"
 fi
